### PR TITLE
Fix bug preventing "Mapbox.getOfflinePacks" from returning on iOS

### LINKED ISSUE #389: getOfflinePacks is not working on ios
hello, after executing "addOfflinePackForRegion" on ios and android, i want to retrieve it somewhere in the app using "getOfflinePacks",

 Mapbox.getOfflinePacks()
      .then(packs => {
        console.log('packs', packs);
      })
      .catch(err => {
        console.error(err); // Handle error
      })

on android, i am getting packs,  but not on ios.

### PR DESCRIPTION
**Pull request by lucaswoj**
@1ec5's [diagnosis and suggested fix](https://github.com/mapbox/react-native-mapbox-gl/issues/389#issuecomment-247823285) is spot on 👍 

fixes #389

cc @1ec5 @bsudekum @dapetcu21

### CODE REVIEW

File: ios/RCTMapboxGL/RCTMapboxGLManager.m [hunk 1]
```diff
@@ -153,7 +153,7 @@ - (id)init
     _loadedPacks = NO;
     
     // Setup pack array loading notifications
-    [[MGLOfflineStorage sharedOfflineStorage] addObserver:self forKeyPath:@"packs" options:0 context:NULL];
+    [[MGLOfflineStorage sharedOfflineStorage] addObserver:self forKeyPath:@"packs" options:NSKeyValueObservingOptionInitial context:NULL];
```
Comment (1ec5) [inline ios/RCTMapboxGL/RCTMapboxGLManager.m:156]: Does this set up a race condition where the pack notification handlers (set up below) aren't created by the time the initial change notification comes in? It would depend on whether the initial change notification is posted synchronously or whether it is posted asynchronously at the end of the current run loop iteration.

Comment (lucaswoj) [reply ios/RCTMapboxGL/RCTMapboxGLManager.m:156]: I have not observed this race condition in practice. Without a deeper understanding of the framework, I can't speak to the theory.
